name: Build and test with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# jobs:
#   job_build_application:
#     runs-on: ubuntu-latest
#     name: Build Java application
#     steps:
#       - name: Update and install prerequisites
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y tree
#       - name: Checkout to branch
#         uses: actions/checkout@v2
#       - name: Create output directory
#         run: |
#           mkdir -p java_app
#           mkdir -p test_results
#           pwd
#           ls -la
#       - name: Create container
#         uses: ./
#         id: build
#       - name: Verify results
#         run: |
#           tree java_app
#           tree test_results
#           ls -la /

jobs:
  BUILD_APPLICATION:
    name: Build Java application
    runs-on: ubuntu-latest
    steps:
      - name: Update and install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
      - name: Checkout to branch
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Verify results
        run: |
          pwd
          echo -e "============================================================"
          ls -la
          echo -e "============================================================"
          ls -la target
  TEST_APPLICATION:
    name: Test builded application
    runs-on: ubuntu-latest
    steps:
      - name: Check directory content
        run: |
          pwd
          echo -e "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
          ls -la
          echo -e "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
          ls -la target
