# Guidelines to build and test applications:
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven
# https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts
# https://github.com/actions/setup-java

name: Build and test with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  BUILD_APPLICATION:
    name: Build Java application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build application with Maven
        run: mvn -B package --file pom.xml
      - name: Create artifactory directory
        run: mkdir staging && cp target/*.jar staging
      - name: Upload to Github artifactory
        uses: actions/upload-artifact@v2
        with:
          name: app_build_package
          path: staging
          retention-days: 1

  TEST_APPLICATION:
    name: Test builded application
    needs: BUILD_APPLICATION
    runs-on: ubuntu-latest
    steps:
      - name: Download builded app from artifactory
        uses: actions/download-artifact@v2
        with:
          name: app_build_package
      - name: Set app name as variable
        run: echo "app name is $(ls xxebenchmark-*.jar)"
